### ISSUE TITLE
key mapping in C16 and lower

### ISSUE THREAD

**Issue by gtxtom** [Arakula/blusb_gui#4]
Occasionally when trying to map keys for C16 and lower, instead of getting a drop down menu with a list of keys; when clicking on the box, it will try and edit the text instead of opening the drop down. It eventually worked when I restarted the program.

![IMG_20190408_083708](https://user-images.githubusercontent.com/49400623/55724656-e66a1d00-59d9-11e9-852e-87d411d6b392.jpg)

**Comment by Arakula** [comment]
Will be fixed in my next upload (tonight, I guess, but it's going to be a long day before I come home, so maybe tomorrow).

**Comment by Arakula** [comment]
I've uploaded the changed source file, so if you can compile it yourself, you don't have to wait for my executable upload, which will come later (I'm connected to the 'net using a 5 GB per month prepaid card right now, so I'm unwilling to upload some megabytes over that :-) ).

**Comment by gtxtom** [comment]
That is fine. I'm in no rush. I managed to get it all working. Thanks for the amazing tool!

**Comment by Arakula** [comment]
Done.
