### ISSUE TITLE
Regular ANSI needs more columns

### ISSUE THREAD

**Issue by gtxtom** [Arakula/blusb_gui#5]
I have a 4th gen Model M with the permanently attached cable and was attempting to map my keys. I have several on my keyboard that map down to column 17. I had to work around this by switching to ANSI 121 and then switching back to standard ANSI but not changing the matrix layout.

**Comment by Arakula** [comment]
Fascinating. I'll have to talk to Jörn about this.

**Comment by gtxtom** [comment]
I emailed with him and this is what he had to say below. I don't think it's a major issue, but it might be nice if the user could add or remove columns/rows as needed?


"I should take a look at the GUI and figure out why you need column 17 when your matrix has only 16 columns. It depends on how the columns are counted, or, in other words, how the microcontroller pins that function as columns are numbered. If you take a look at the controller board, you'll see that I mounted the pin header right above the rectangular solder pads for the FFC socket, such that there are two unused round solder pads to the left and right of the pin header. If you start counting from either the left or the right, the total number of columns will always be off by 2 because column 0 and 1 are not actually connected, so you should start counting at 2, and stop counting at 17, which gives 16 columns. I could have done otherwise, because it doesn't really make a difference. I could have soldered the pin header to pads 0 to 15 or 4 to 19, but I decided to use pads 2 to 17. However, actually that shouldn't make a difference because pads 2 to 17 are connected to the very same microcontroller pins I use for all 16 column matrices."

**Comment by Arakula** [comment]
All newer BlUsb controllers use 20 columns internally anyway, so I changed the GUI now to reflect that. It's always showing 20 columns now.
